# Generated by Neurodocker version 0.6.0
# Timestamp: 2019-10-23 09:02:43 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/kaczmarj/neurodocker

FROM neurodebian:stretch-non-free

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV FSLDIR="/opt/fsl-6.0.1" \
    PATH="/opt/fsl-6.0.1/bin:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           sudo \
           wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FSL ..." \
    && mkdir -p /opt/fsl-6.0.1 \
    && curl -fsSL --retry 5 https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.1-centos6_64.tar.gz \
    | tar -xz -C /opt/fsl-6.0.1 --strip-components 1 \
    && sed -i '$iecho Some packages in this Docker container are non-free' $ND_ENTRYPOINT \
    && sed -i '$iecho If you are considering commercial use of this container, please consult the relevant license:' $ND_ENTRYPOINT \
    && sed -i '$iecho https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence' $ND_ENTRYPOINT \
    && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $ND_ENTRYPOINT \
    && echo "Installing FSL conda environment ..." \
    && bash /opt/fsl-6.0.1/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.1 \
    && echo "Downgrading deprecation module per https://github.com/kaczmarj/neurodocker/issues/271#issuecomment-514523420" \
    && /opt/fsl-6.0.1/fslpython/bin/conda install -n fslpython -c conda-forge -y deprecation==1.* \
    && echo "Removing bundled with FSLeyes libz likely incompatible with the one from OS" \
    && rm -f /opt/fsl-6.0.1/bin/FSLeyes/libz.so.1

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           openbox \
           tightvncserver \
           xfonts-base \
           xterm \
           xvfb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo 'Configuring VNC password ...' \
    && mkdir -p ~/.vnc \
    && echo neuroimg | vncpasswd -f > ~/.vnc/passwd \
    && chmod 0600 ~/.vnc/passwd \
    && sed -i '$iexport USER=$(whoami)' $ND_ENTRYPOINT \
    && sed -i '$iexport DISPLAY=$HOSTNAME:1' $ND_ENTRYPOINT \
    && sed -i '$ivncserver -geometry 1600x1200' $ND_ENTRYPOINT

RUN test "$(getent passwd neuro)" || useradd --no-user-group --create-home --shell /bin/bash neuro
USER neuro

WORKDIR /home/neuro

ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean --all && sync \
    && conda create -y -q --name neuro_py37 \
    && conda install -y -q --name neuro_py37 \
           "python=3.7" \
           "jupyter" \
           "nbgrader" \
           "jupyter_contrib_nbextensions" \
           "matplotlib" \
           "scikit-learn" \
           "seaborn" \
    && sync && conda clean --all && sync \
    && bash -c "source activate neuro_py37 \
    &&   pip install --no-cache-dir  \
             "nilearn" \
             "nibabel"" \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate neuro_py37' $ND_ENTRYPOINT

RUN curl -L https://github.com/krallin/tini/releases/download/v0.6.0/tini > tini && chmod +x tini

RUN sed -i '$i~/tini -- jupyter notebook --ip=0.0.0.0 --port 9999 &> /dev/null &' $ND_ENTRYPOINT

COPY [".", "/home/neuro/"]

RUN mv course_settings_container.yml course_settings.yml

RUN mkdir -p ~/.jupyter && echo c.NotebookApp.ip = \"0.0.0.0\" > ~/.jupyter/jupyter_notebook_config.py

RUN bash -c 'source activate neuro_py37 && pip install . && jupyter nbextension install --sys-prefix --py nbgrader --overwrite && jupyter nbextension enable --sys-prefix --py nbgrader && jupyter serverextension enable --sys-prefix --py nbgrader'

EXPOSE 9999

EXPOSE 5901

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "neurodebian:stretch-non-free" \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "vim" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "fsl", \
    \n      { \
    \n        "version": "6.0.1" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "vnc", \
    \n      { \
    \n        "passwd": "neuroimg", \
    \n        "start_at_runtime": true \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "neuro" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/home/neuro" \
    \n    ], \
    \n    [ \
    \n      "miniconda", \
    \n      { \
    \n        "conda_install": [ \
    \n          "python=3.7", \
    \n          "jupyter", \
    \n          "nbgrader", \
    \n          "jupyter_contrib_nbextensions", \
    \n          "matplotlib", \
    \n          "scikit-learn", \
    \n          "seaborn" \
    \n        ], \
    \n        "pip_install": [ \
    \n          "nilearn", \
    \n          "nibabel" \
    \n        ], \
    \n        "create_env": "neuro_py37", \
    \n        "activate": true \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "curl -L https://github.com/krallin/tini/releases/download/v0.6.0/tini > tini && chmod +x tini" \
    \n    ], \
    \n    [ \
    \n      "add_to_entrypoint", \
    \n      "~/tini -- jupyter notebook --ip=0.0.0.0 --port 9999 &> /dev/null &" \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        ".", \
    \n        "/home/neuro/" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mv course_settings_container.yml course_settings.yml" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir -p ~/.jupyter && echo c.NotebookApp.ip = \\\"0.0.0.0\\\" > ~/.jupyter/jupyter_notebook_config.py" \
    \n    ], \
    \n    [ \
    \n      "run_bash", \
    \n      "source activate neuro_py37 && pip install . && jupyter nbextension install --sys-prefix --py nbgrader --overwrite && jupyter nbextension enable --sys-prefix --py nbgrader && jupyter serverextension enable --sys-prefix --py nbgrader" \
    \n    ], \
    \n    [ \
    \n      "expose", \
    \n      [ \
    \n        "9999" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "expose", \
    \n      [ \
    \n        "5901" \
    \n      ] \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
